import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Plus, Trash2, Upload } from 'lucide-react';
import { api, type Content } from '../lib/content';
import KineticSculpture from './KineticSculpture';
type Artwork=Content['heroArtwork'];
export default function HeroArtworkEditor({value,onChange,csrf,initials,owner,accent}:{value:Artwork;onChange:(next:Artwork)=>void;csrf:string;initials:string;owner:string;accent:string}){
  const [uploading,setUploading]=useState(false),[error,setError]=useState('');
  const latest=useRef({value,onChange}),mounted=useRef(true);
  useEffect(()=>{latest.current={value,onChange};},[value,onChange]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const update=(patch:Partial<Artwork>)=>onChange({...value,...patch});
  const upload=async(file:File)=>{
    setError('');if(file.size>3*1024*1024){setError('Choose a logo under 3 MB.');return;}
    if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Use PNG, JPEG or WebP.');return;}
    setUploading(true);
    try{
      const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read the logo.'));reader.readAsDataURL(file);});
      const result=await api<{url:string}>('/api/uploads',{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify({data,kind:'logo'})});
      if(mounted.current)latest.current.onChange({...latest.current.value,logo:result.url});
    }catch(e){if(mounted.current)setError((e as Error).message);}finally{if(mounted.current)setUploading(false);}
  };
  return <div className="hero-artwork-editor"><div className="admin-panel hero-artwork-controls">
    <label>Show in the hero<select value={value.mode} onChange={e=>update({mode:e.target.value})}><option value="logo">My logo</option><option value="text">Text slides</option></select></label>
    {value.mode==='logo'?<div className="hero-logo-controls" tabIndex={0} aria-label="Logo upload. Paste an image here or use Upload logo." onPaste={event=>{const file=Array.from(event.clipboardData.items).find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){event.preventDefault();void upload(file);}}}><p>{value.logo?'Your uploaded logo':'Using your current '+initials+' ✳ brand mark'}</p><label className="upload-button"><Upload size={16}/>{uploading?'Uploading…':'Upload logo'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label><small className="field-hint">Upload or paste a PNG, JPEG or WebP. A transparent background works best. Up to 3 MB. White backgrounds are removed from the dot effect.</small>{value.logo&&<button className="text-link" onClick={()=>update({logo:''})}>Use original brand mark</button>}</div>:<div className="hero-slide-editor"><p className="field-hint">Up to 12 slides. Each slide can contain 60 characters (including spaces) and up to 3 lines. Text wraps automatically; Enter adds a line break. Visitors click or tap to see the next slide.</p>{value.phrases.map((text,index)=><div className="hero-slide" key={index}><label>Slide {index+1}<textarea aria-label={`Slide ${index+1}`} rows={3} maxLength={60} value={text} onChange={e=>update({phrases:value.phrases.map((item,i)=>i===index?e.target.value:item)})}/></label><div className="hero-slide-meta"><small>{text.length} / 60 characters</small><div><button className="icon-button" aria-label={`Move slide ${index+1} up`} disabled={index===0} onClick={()=>{const phrases=[...value.phrases];[phrases[index-1],phrases[index]]=[phrases[index],phrases[index-1]];update({phrases});}}><ArrowUp size={16}/></button><button className="icon-button" aria-label={`Move slide ${index+1} down`} disabled={index===value.phrases.length-1} onClick={()=>{const phrases=[...value.phrases];[phrases[index+1],phrases[index]]=[phrases[index],phrases[index+1]];update({phrases});}}><ArrowDown size={16}/></button><button className="icon-button" aria-label={`Remove slide ${index+1}`} disabled={value.phrases.length===1} onClick={()=>update({phrases:value.phrases.filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></div></div>{(!text.trim()||text.split('\n').length>3)&&<p className="error" role="alert">Enter some text using no more than 3 lines.</p>}</div>)}<button className="button outline" disabled={value.phrases.length>=12} onClick={()=>update({phrases:[...value.phrases,'New idea']})}><Plus size={16}/>Add slide</button></div>}
    <div className="hero-caption-controls"><label className="toggle-field"><input type="checkbox" checked={value.showCaption} onChange={e=>update({showCaption:e.target.checked})}/><span>Show caption below artwork</span></label>{value.showCaption&&<label>Caption<input aria-label="Caption" maxLength={40} value={value.caption} onChange={e=>update({caption:e.target.value})}/><small className="field-hint">{value.caption.length} / 40 characters. For example: Play with possibility.</small></label>}<label className="toggle-field"><input type="checkbox" checked={value.showEyebrow} onChange={e=>update({showEyebrow:e.target.checked})}/><span>Show text above artwork</span></label>{value.showEyebrow&&<label>Text above artwork<input maxLength={80} value={value.eyebrow} onChange={e=>update({eyebrow:e.target.value})}/></label>}</div>{error&&<p role="alert" className="error">{error}</p>}
  </div><div className="hero-artwork-preview"><p className="eyebrow">LIVE PREVIEW</p><KineticSculpture artwork={value} initials={initials} owner={owner} accent={accent}/><p className="field-hint">Your changes go live when you publish.</p></div></div>;
}
